### ISSUE TITLE
"Inquire in the Spring Cleaning Chem.SE chat room for repository access"

### ISSUE THREAD

**Issue by GaurangTandon** [ChemSECleanup/homework-cleanup#1]
I can already access this repository. Is this a bug? Also, this repository seems inactive, did the actual things happen elsewhere, or was everything cleared up after it was done?

You might also want to update README.md accordingly. Thanks!

**Comment by bskinn** [comment]
@GaurangTandon Nope, this repository is public, you *should* be able to see it, open issues, etc.

What's still protected is the *organization*.  The planning work was done on projects opened at the organization level.

I'll invite you to the group in a sec here.

**Comment by GaurangTandon** [comment]
Thanks for adding me in! :-) Though it seems the entire planning was completed last year itself ^_^

**Comment by bskinn** [comment]
Yeah, once [reaction] got blacklisted/scrubbed, the GH project wasn't useful for tracking it.  If we were to seriously attack [homework], though, we might revive things here.

**Comment by GaurangTandon** [comment]
We might wait for Martin to be back so that the mod team is fully reinforced, and I guess then we can start having fun with [homework] also. Let's see how soon this starts. To me, June this year seems ideal.

**Comment by bskinn** [comment]
Be prepared for things to go far more slowly than you might like. :-)

**Comment by GaurangTandon** [comment]
Ah, that's definitely true :P
